variable "region_name" {}
variable "bucketname" {}
variable "acl" {}
variable "env" {}
variable "versioning_enabled" {}
variable "function_name" {}
variable "lambda_handler" {}
variable "runtime" {}
variable "lambda_execution_role" {}
variable "s3_bucket" {}
variable "s3_key" {}
variable "cwrulename" {}
variable "schedule" {}
variable "target_id" {}
variable "statement_id2" {}
variable "action2" {}
variable "principle2" {}
variable "event_bucket_name" {}
variable "event_type" {}
variable "prefix" {}
variable "suffix" {}
variable "statement_id1" {}
variable "action1" {}
variable "principle1" {}
variable "source_arn" {}
